config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("todo_list.urls", namespace="todo_list"))
]

todo_list/urls.py
from django.urls import path

from todo_list.views import (
    TagListView,
    TaskListView,
    TaskCreateView,
    TagCreateView,
    TaskUpdateView,
    TagUpdateView,
    TaskDeleteView,
    TagDeleteView, CompleteTaskView, UndoTaskView
)

urlpatterns = [
    path("", TaskListView.as_view(), name="index"),
    path("create/", TaskCreateView.as_view(), name="task-create"),
    path("<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
    path("<int:pk>/complete/", CompleteTaskView.as_view(), name="task-complete"),
    path("<int:pk>/undo/", UndoTaskView.as_view(), name="task-undo"),
]

app_name = "todo_list"

todo_list/models.py
from datetime import datetime, timedelta

from django.db import models


class Tag (models.Model):
    name = models.CharField(max_length=63)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(default=datetime.now() + timedelta(weeks=1))
    is_done = models.BooleanField(default=False)
    tag = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ["is_done", "deadline"]

    def __str__(self):
        return self.content

todo_list/forms.py
from datetime import timedelta

from django import forms
from django.core.exceptions import ValidationError
from django.utils import timezone

from todo_list.models import Tag, Task


class TaskForm(forms.ModelForm):
    deadline = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}))
    tag = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Task
        fields = "__all__"

    def clean_deadline(self):
        cleaned_data = super().clean()
        deadline = cleaned_data.get("deadline", timezone.now())

        if deadline < timezone.now():
            raise ValidationError("Deadline cannot be before the creation of the task.")
        if deadline <= timezone.now() + timedelta(minutes=30):
            raise ValidationError("Deadline must be at least 30 minutes from the creation of the task.")

        return cleaned_data

todo_list/views.py
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic, View

from todo_list.forms import TaskForm
from todo_list.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    template_name = "todo_list/index.html"


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo_list:index")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo_list:index")


class TaskDeleteView(generic.DeleteView):
    model = Task
    template_name = "todo_list/task_confirm_delete.html"
    success_url = reverse_lazy("todo_list:index")


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo_list:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("todo_list:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    template_name = "todo_list/tag_confirm_delete.html"
    success_url = reverse_lazy("todo_list:tag-list")


class CompleteTaskView(View):
    def get(self, request, pk):
        task = get_object_or_404(Task, pk=pk)
        task.is_done = True
        task.save()
        return redirect('todo_list:index')


class UndoTaskView(View):
    def get(self, request, pk):
        task = get_object_or_404(Task, pk=pk)
        task.is_done = False
        task.save()
        return redirect('todo_list:index')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}
    <title>Todo List</title>
  {% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
        crossorigin="anonymous">
</head>

<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
        {% block sidebar %}
          {% include "includes/sidebar.html" %}
        {% endblock %}
      </div>

      <div class="col-sm-9">
        {% block content %}{% endblock %}
        <br>

      </div>
    </div>
  </div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group mt-3">
  <li class="list-group-item"><a href="{% url "todo_list:index" %}">Home</a></li>
  <li class="list-group-item"><a href="{% url "todo_list:tag-list" %}">Tags</a></li>
</ul>

templates/todo_list/index.html
{% extends "base.html" %}

{% block content %}
<h1 class="mt-3">TODO List
  <a href="{% url 'todo_list:task-create' %}" class="btn btn-primary link-to-page float-right">
    Add task
  </a>
</h1>
<br>
<ul>
  {% for task in task_list %}
    <li>
      <p><strong>{{ task.content }}</strong>
      {% if task.is_done %}
        <strong class="text-success">Done</strong>
      {% else %}
        <strong class="text-danger">Not done</strong>
      {% endif %}

      {% if not task.is_done %}
        <a class="btn btn-success float-right" href="{% url 'todo_list:task-complete' pk=task.id %}">
          Complete
        </a>
      {% else %}
        <a class="btn btn-secondary float-right" href="{% url 'todo_list:task-undo' pk=task.id %}">
          Undo
        </a>
      {% endif %}

      </p>
      <p>Created: {{ task.created_at }}
        {% if not task.is_done %}
          <text class="text-danger">Deadline: {{ task.deadline }}</text>
        {% endif %}
      </p>
      <p class="text-muted font-weight-bold">Tags: {% for tag in task.tag.all %}
      {{ tag.name }}
      {% endfor %}
      <a href="{% url 'todo_list:task-update' pk=task.id %}">Update </a>
      <a class="text-danger" href="{% url 'todo_list:task-delete' pk=task.id %}">Delete </a>
      </p>
    </li>
    <hr>
  {% endfor %}
</ul>
{% endblock %}

templates/todo_list/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="d-flex justify-content-center">
    <div>
      <h1 class="text-center font-weight-bold">Are you sure you want to delete tag?</h1>
      <form action="" method="post">
        {% csrf_token %}
        <div class="text-center">
          <input type="submit" value="Yes" class="btn btn-danger">
          <a href="{% url 'todo_list:tag-list' %}" class="btn btn-primary link-to-page">
            No
          </a>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

templates/todo_list/tag_create.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1 class="font-weight-bold">{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo_list/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1 class="font-weight-bold">{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo_list/tag_list.html
{% extends "base.html" %}

{% block content %}
<h1 class="mt-3"> Tags
  <a href="{% url 'todo_list:tag-create' %}" class="btn btn-primary link-to-page float-right">
    Add
  </a>
</h1>
  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
    {% for tag in tag_list %}
      <tr>
        <td>{{ tag.name }}</td>
        <td>
          <a class="btn btn-primary" href="{% url 'todo_list:tag-update' pk=tag.id %}">Update</a>
        </td>
        <td>
          <a class="btn btn-danger" href="{% url 'todo_list:tag-delete' pk=tag.id %}">Delete</a>
        </td>
      </tr>
    {% endfor %}
    </table>
    {% else %}
    <p><strong>No tags!</strong></p>
  {% endif %}

{% endblock %}

templates/todo_list/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="d-flex justify-content-center">
    <div>
      <h1 class="text-center font-weight-bold">Are you sure you want to delete task?</h1>
      <form action="" method="post">
        {% csrf_token %}
        <div class="text-center">
          <input type="submit" value="Yes" class="btn btn-danger">
          <a href="{% url 'todo_list:index' %}" class="btn btn-primary link-to-page">
            No
          </a>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

templates/todo_list/task_create.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1 class="font-weight-bold">{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo_list/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1 class="font-weight-bold">{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}